services:
  web: 
    image: php:8.2-fpm
    working_dir: /var/www/html
    volumes:
      - '.:/var/www/html'
    ports:
      - '7001:80'
    environment:
      - APP_URL=${SERVICE_FQDN_EASYAPPOINTMENTS_80}
      - APP_LANGUAGE=pt-BR
      - DEBUG_MODE=false
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=${SERVICE_PASSWORD_MYSQL}
      - DB_NAME=easyappointments
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_SYNC_FEATURE=${GOOGLE_SYNC_FEATURE:-false}
    command: 
      - /bin/sh
      - -c
      - |
        apt update && apt install -y curl
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 18
        nvm use 18
        npm install
        npm run build
  mysql:
    image: 'mysql:8.0'
    volumes:
      - 'mysql_data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${SERVICE_PASSWORD_ROOT_MYSQL}
      - MYSQL_DATABASE=${SERVICE_DATABASE_MYSQL}
      - MYSQL_USER=${SERVICE_USER_MYSQL}
      - MYSQL_PASSWORD=${SERVICE_PASSWORD_MYSQL}

  mailpit:
    image: 'axllent/mailpit:v1.7'
    ports:
      - '8025:8025'
      - '1025:1025'

  swagger-ui:
    platform: linux/amd64
    image: swaggerapi/swagger-ui:v5.10.5
    ports:
      - "7002:8080"
    volumes:
      - ./openapi.yml:/usr/share/nginx/html/openapi.yml
    environment:
      API_URL: openapi.yml
  
  baikal:
    image: ckulka/baikal:0.9.4-apache
    ports:
      - "7003:80"
    volumes:
      - baikal_data:/var/www/html

volumes:
  mysql_data:
  baikal_data:
