services:
  web: 
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ".:/var/www/html"
    ports:
      - '7001:80'
    environment:
      - APP_URL=${SERVICE_FQDN_EASYAPPOINTMENTS_80}
      - APP_LANGUAGE=pt-BR
      - DEBUG_MODE=false
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=${SERVICE_PASSWORD_MYSQL}
      - DB_NAME=easyappointments
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_SYNC_FEATURE=${GOOGLE_SYNC_FEATURE:-false}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_CRYPTO=${SMTP_CRYPTO:-tls}
      - SMTP_PORT=${SMTP_PORT:-587}
      - FROM_NAME=${FROM_NAME}
      - FROM_ADDRESS=${FROM_ADDRESS}
      - REPLY_TO=${REPLY_TO}
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 5s
  mysql:
    image: 'mysql:8.0'
    volumes:
      - 'mysql_data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${SERVICE_PASSWORD_ROOT_MYSQL}
      - MYSQL_DATABASE=${SERVICE_DATABASE_MYSQL}
      - MYSQL_USER=${SERVICE_USER_MYSQL}
      - MYSQL_PASSWORD=${SERVICE_PASSWORD_MYSQL}
  swagger-ui:
    platform: linux/amd64
    image: swaggerapi/swagger-ui:v5.10.5
    ports:
      - "7002:8080"
    volumes:
      - ./openapi.yml:/usr/share/nginx/html/openapi.yml
    environment:
      API_URL: openapi.yml
  
  baikal:
    image: ckulka/baikal:0.9.4-apache
    ports:
      - "7003:80"
    volumes:
      - baikal_data:/var/www/html

volumes:
  mysql_data:
  baikal_data:
